# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
profiles:
  resource: "@ProfilesBundle/Resource/config/routing/internal.xml"